Refactoring
sava-cska/SPbSU-EMKN pull request #16
Opened 2022-10-13 22:25 UTC by sava-cska

2022-10-14 11:40 UTC, ainurbl requested changes

2022-10-14 11:40 UTC, ainurbl commented on server/internal/app/actions/base/emkn_action.go
> +			error_handler.HandleError(context.Logger, responseWriter, http.StatusBadRequest, "Can't parse httpRequest.", errJSON)
а почему не errorHandler?

2022-10-14 11:40 UTC, ainurbl commented on server/internal/app/services/request_response/parser.go
> +package request_response
потенциально не только их парсим. давай другой нейминг?

2022-10-14 19:27 UTC, sava-cska commented on server/internal/app/actions/base/emkn_action.go
> +			error_handler.HandleError(context.Logger, responseWriter, http.StatusBadRequest, "Can't parse httpRequest.", errJSON)
Договорились, что это пакет

2022-10-14 19:27 UTC, sava-cska commented on server/internal/app/services/request_response/parser.go
> +package request_response
Поправил на http_parser

2022-10-15 08:33 UTC, ainurbl approved these changes

2022-10-15 13:57 UTC, merged