MSCSE-58,59,60
sava-cska/SPbSU-EMKN pull request #20
Opened 2022-10-21 20:11 UTC by ilyavoronin

2022-10-22 06:33 UTC, ainurbl requested changes

2022-10-22 06:33 UTC, ainurbl commented on server/internal/app/actions/courses/description_action.go
> +func HandleDescription(request *DescriptionRequest, context *dependency.DependencyContext) (int, *DescriptionResponse) {
я бы ручки продолжил бы писать с полным путем. так как мы через post всё делаем, потенциально может встретиться profiles/get и courses/get

2022-10-22 06:33 UTC, ainurbl commented on server/internal/app/actions/courses/description_response.go
> +type DescriptionResponse struct {
везде в респонсах договор что посылаем ответ в поле Response, например см https://github.com/sava-cska/SPbSU-EMKN/blob/main/server/internal/app/actions/profiles/get_response.go#L14

2022-10-22 06:33 UTC, ainurbl commented on server/internal/app/actions/courses/description_response.go
> +type DescriptionResponse struct {
возможно можно порефакторить, чтобы каждый раз не писать одно и то же

2022-10-22 06:33 UTC, ainurbl commented on server/internal/app/actions/courses/descriptionping_action.go
> +	changed := timestamp.UnixMilli() > int64(request.LastSyncTime)
может тогда уж сделать тип у LastSyncTime сразу int64?

2022-10-22 06:33 UTC, ainurbl commented on server/internal/app/actions/courses/descriptionping_response.go
> +type DescriptionPingResponse struct {
то же про респонс

2022-10-22 06:33 UTC, ainurbl commented on server/internal/app/models/courses.go
> +type Period struct {
я лично за разделение структур для ручек и структур для всего остального
мне кажется тут json пометки не должны быть

2022-10-22 06:33 UTC, ainurbl commented on server/internal/app/storage/sql_scripts/courses_base.sql
> +CREATE TABLE COURSES_BASE (
COURSES_BASE to lowercase

2022-10-22 06:33 UTC, ainurbl commented on server/internal/app/storage/sql_scripts/periods_base.sql
> +CREATE TABLE PERIODS_BASE (
PERIODS_BASE to lowercase

2022-10-22 06:33 UTC, ainurbl commented on server/internal/app/storage/storage.go
> +	coursesDAO        *CoursesDao
CoursesDao -> CoursesDAO [data access object]

2022-10-23 16:16 UTC, ainurbl commented
также надо будет после моего коммита немного переделать ручки.

2022-10-24 21:09 UTC, ilyavoronin commented on server/internal/app/models/courses.go
> +type Period struct {
Не вижу смысла персоздавать структуру, если мы ее отсылаем полностью в таком же виде. Потом еще придется for-ом проходить и пересоздавать структуры.
 Это всего лишь json разметки. Могло бы быть плохо с точки зрения циклических зависимостей, но мы же не собираемся импортировать модуль courses в модуль models. А наобором выглядит вполне логично

2022-10-25 08:37 UTC, ainurbl approved these changes

2022-10-25 09:27 UTC, sava-cska requested changes

2022-10-25 09:27 UTC, sava-cska commented on server/internal/app/actions/courses/descriptionping_action.go
> +	println("%d %d", timestamp.UnixMilli(), request.LastSyncTime)
Сделай это логгированием

2022-10-25 09:31 UTC, ilyavoronin commented on server/internal/app/actions/courses/descriptionping_action.go
> +	println("%d %d", timestamp.UnixMilli(), request.LastSyncTime)
Не, я это удалю просто, забыл убрать. Это отладочный вывод, который я добавил после того как перепутал название поля  в запросе при тестировании и у меня всегда LastSyncTime был 0

2022-10-25 09:41 UTC, sava-cska commented on server/internal/app/actions/courses/descriptionping_action.go
> +	println("%d %d", timestamp.UnixMilli(), request.LastSyncTime)
У тебя нет никакого логгирования трёх методов :(
Кажется, что время - это нормальная отладочная информация

2022-10-25 10:46 UTC, sava-cska approved these changes

2022-10-26 18:41 UTC, merged