MSCSE-34: Add validate_email handler
sava-cska/SPbSU-EMKN pull request #4
Opened 2022-10-02 18:46 UTC by sava-cska

2022-10-02 20:40 UTC, ainurbl requested changes

2022-10-02 20:40 UTC, ainurbl commented on server/internal/app/actions/accounts/errors_response.go
> +type ErrorsList struct {
наверное семантически более верно назвать ErrorsUnion и порадовать Даню

2022-10-02 20:40 UTC, ainurbl commented on server/internal/app/actions/accounts/errors_response.go
> +type Error struct{}
пробел перед {

2022-10-02 20:40 UTC, ainurbl commented on server/internal/app/actions/accounts/validate_email_action.go
> +	if expireTime.Before(time.Now()) {
я бы АСАП звал time.Now(), прям при самом начале запроса

2022-10-02 20:40 UTC, ainurbl commented on server/internal/app/storage/user_dao.go
>  import (
надо мувнуть этот файл в /storage

2022-10-02 20:40 UTC, ainurbl commented on server/internal/app/actions/accounts/validate_email_action.go
> +			if errAdd := storage.UserDAO().AddUser(&user); errAdd != nil {
по-хорошему бы сделать ретраи, но не блокер

2022-10-02 22:33 UTC, sava-cska commented on server/internal/app/actions/accounts/errors_response.go
> +type ErrorsList struct {
Исправил

2022-10-02 22:35 UTC, sava-cska commented on server/internal/app/actions/accounts/errors_response.go
> +type Error struct{}
Автоформатирование не позволяет так сделать :(
Либо `type Error struct{}`, либо 
```
type Error struct {
}
```

2022-10-02 22:36 UTC, sava-cska commented on server/internal/app/storage/user_dao.go
>  import (
Он и так там...

2022-10-02 22:39 UTC, sava-cska commented on server/internal/app/actions/accounts/validate_email_action.go
> +			if errAdd := storage.UserDAO().AddUser(&user); errAdd != nil {
Почему ретраи? У нас может быть так, что два пользователя одновременно регистрируются с одинаковыми логинами, тогда опоздавшего мы никогда не сможем добавить в базу. Или ты хочешь, чтобы я пробовал добавить ~3-5 раз? Не особо понимаю, зачем это.

2022-10-02 22:41 UTC, sava-cska commented on server/internal/app/actions/accounts/validate_email_action.go
> +	if expireTime.Before(time.Now()) {
Поправил

2022-10-03 05:41 UTC, ainurbl commented on server/internal/app/actions/accounts/errors_response.go
> +type Error struct{}
удивительно, прошу прощения

2022-10-03 05:41 UTC, ainurbl commented on server/internal/app/storage/user_dao.go
>  import (
капитальная шиза

2022-10-03 05:42 UTC, ainurbl commented on server/internal/app/actions/accounts/validate_email_action.go
> +			if errAdd := storage.UserDAO().AddUser(&user); errAdd != nil {
ну бд же не 100% добавит даже если добавлять просто так, а если другой юзер есть, то ретраи 5 раз упадут ну и ладно

2022-10-03 05:43 UTC, ainurbl approved these changes

2022-10-03 06:02 UTC, merged