MSCSE-35, MSCSE-37
sava-cska/SPbSU-EMKN pull request #5
Opened 2022-10-02 20:36 UTC by ilyavoronin

2022-10-03 19:40 UTC, sava-cska commented
Запусти `gofmt -w .` в папке `server`, чтобы он отформатировал весь код в твоём проекте.

2022-10-03 19:42 UTC, sava-cska commented
Создавай для каждого действия свой `response` и `request` файл. Не создавай для них структуры в `action` файлах.

2022-10-03 20:03 UTC, sava-cska requested changes

2022-10-03 20:03 UTC, sava-cska commented on server/internal/app/actions/accounts/login_action.go
> +			writer.WriteHeader(http.StatusBadRequest)
Воспользуйся utils.handleError

2022-10-03 20:03 UTC, sava-cska commented on server/internal/app/actions/accounts/login_action.go
> +		logger.Errorf("Failed to read password for login %s: %s", login, err.Error())
Не пиши тут в logger, запиши текст ошибки в error и кидай наверх. Там ты всё равно вызовешь handleError

2022-10-03 20:03 UTC, sava-cska commented on server/internal/app/actions/accounts/login_action.go
> +}
`return password == origPassword, nil`

2022-10-03 20:03 UTC, sava-cska commented on server/internal/app/actions/accounts/login_action.go
> +func ValidateUserCredentials(login string, password string, logger *logrus.Logger, storage *storage.Storage) (bool, error) {
Эту функцию надо назвать с маленькой буквы. В go видимость функций между файлами определяется не public/private, а с маленькой или с большой буквы называется функция. Маленькая = private, большая = public.

2022-10-03 20:03 UTC, sava-cska commented on server/internal/app/actions/accounts/login_action.go
> +type loginRequest struct {
Вынеси в request-файл

2022-10-03 20:03 UTC, sava-cska commented on server/internal/app/actions/accounts/validate_change_password_action.go
> +			writer.WriteHeader(http.StatusBadRequest)
utils.handleError

2022-10-03 20:03 UTC, sava-cska commented on server/internal/app/actions/accounts/validate_change_password_action.go
> +			writer.WriteHeader(http.StatusBadRequest)
utils.handleError

2022-10-03 20:03 UTC, sava-cska commented on server/internal/app/actions/accounts/validate_change_password_action.go
> +			writer.WriteHeader(http.StatusOK)
Сделай переменную returnCode и присвой ей в двух ветках значение. Старайся писать во writer как можно реже в коде

2022-10-03 20:03 UTC, sava-cska commented on server/internal/app/actions/accounts/validate_change_password_action.go
> +type ValidateChangePasswordRequest struct {
Структуры в response и request файлы

2022-10-03 20:03 UTC, sava-cska commented on server/internal/app/server.go
> +			response.WriteHeader(http.StatusUnauthorized)
utils.handleError

2022-10-03 20:03 UTC, sava-cska commented on server/internal/app/server.go
> +			response.WriteHeader(http.StatusUnauthorized)
utils.handleError

2022-10-03 20:03 UTC, sava-cska commented on server/internal/app/server.go
> +			response.WriteHeader(http.StatusUnauthorized)
utils.handleError

2022-10-03 20:03 UTC, sava-cska commented on server/internal/app/server.go
> +			response.WriteHeader(http.StatusInternalServerError)
utils.handleError

2022-10-03 20:03 UTC, sava-cska commented on server/internal/app/server.go
> +			response.WriteHeader(http.StatusUnauthorized)
utils.handleError

2022-10-03 20:03 UTC, sava-cska commented on server/internal/app/storage/change_password_dao.go
> +	if err != nil {
if err := ...; err != nil {

}

2022-10-03 20:03 UTC, sava-cska commented on server/internal/app/storage/change_password_dao.go
> +	row := cpd.Storage.Db.QueryRow(`
Я не уверен, сохраняются ли в таких кавычках табы. Давай лучше использовать "...\n" + "...\n"

2022-10-03 20:03 UTC, sava-cska commented on server/internal/app/storage/change_password_dao.go
> +	_, err := cpd.Storage.Db.Exec(`
Аналогично про "\n" + "\n"

2022-10-03 20:03 UTC, sava-cska commented on server/internal/app/storage/user_dao.go
> +		`SELECT password
Аналогично про "\n" + "\n"

2022-10-03 20:03 UTC, sava-cska commented on server/internal/app/storage/user_dao.go
> +	err := row.Scan(&pwd)
if err := ...; err != nil

2022-10-03 20:10 UTC, ilyavoronin commented on server/internal/app/actions/accounts/login_action.go
> +func ValidateUserCredentials(login string, password string, logger *logrus.Logger, storage *storage.Storage) (bool, error) {
Ну да. Она и должа быть public. Потому что в том числе будет использоваться для проверки логина/пароля для всех запросов

2022-10-03 20:12 UTC, ilyavoronin commented on server/internal/app/storage/change_password_dao.go
> +	row := cpd.Storage.Db.QueryRow(`
При чем тут табы? В GoLand если писать в таких кавычках(или в одну строку) синтаксис подсвечивается. Так что я считаю что все другие запросы должны так же писаться, если мы прям хотим чтобы все выглядело одинаково

2022-10-03 20:13 UTC, sava-cska commented on server/internal/app/actions/accounts/login_action.go
> +func ValidateUserCredentials(login string, password string, logger *logrus.Logger, storage *storage.Storage) (bool, error) {
Да, я позже увидел и забыл убрать

2022-10-03 20:17 UTC, sava-cska commented on server/internal/app/storage/change_password_dao.go
> +	row := cpd.Storage.Db.QueryRow(`
Косые кавычки полностью сохраняют строку со всеми переносами и, наверное, со всей табуляцией. Я не очень понимаю, зачем нам нужно тянуть лишние символы в запрос. А ещё подсветки синтаксиса нет в vsCode, так что аргумент про GoLand мимо :)

2022-10-03 21:03 UTC, ilyavoronin commented on server/internal/app/storage/user_dao.go
> +	err := row.Scan(&pwd)
Там не на nil проверка

2022-10-03 21:06 UTC, ilyavoronin commented on server/internal/app/storage/change_password_dao.go
> +	row := cpd.Storage.Db.QueryRow(`
Ну это официальный синтаксис языка Go для многострочных литералов. Я уверен и vsCode его поддерживает(хотя и не выделяет синтаксис sql). Так что если мы хотим консистентности, то нужно определенно его использовать. А лишний символ(и не один) это \n в конце каждой строки

2022-10-03 21:08 UTC, sava-cska commented on server/internal/app/storage/user_dao.go
> +	err := row.Scan(&pwd)
Заметил

2022-10-03 22:22 UTC, sava-cska requested changes

2022-10-03 22:22 UTC, sava-cska commented on server/internal/app/actions/accounts/validate_change_password_action.go
> +		body, err := json.Marshal(&responseBody)
err never user

2022-10-03 22:22 UTC, sava-cska commented on server/internal/app/actions/accounts/login_action.go
> +		return false, errors.New(fmt.Sprintf("Failed to read password for login %s: %s", login, err.Error()))
Используй fmt.Errorf() вместо errors.New(fmt.Sprintf())

2022-10-03 22:22 UTC, sava-cska commented on server/internal/app/storage/change_password_dao.go
> +	row := cpd.Storage.Db.QueryRow(`
Ладно, давай так оставим, но поменяй тогда символы во всех других командах

2022-10-04 09:32 UTC, sava-cska requested changes

2022-10-04 09:32 UTC, sava-cska commented on server/internal/app/actions/accounts/validate_change_password_action.go
> +		_, _ = writer.Write(body)
Так нельзя делать. Когда ты вызываешь HandleError, ты сообщаешь о произошедшей ошибке и после этого сразу должен сделать return. И только если не было ни одной ошибки, ты пишешь во writer returnCode и body

2022-10-04 14:15 UTC, sava-cska approved these changes

2022-10-04 14:15 UTC, merged